name: Main CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  IMAGE: sxiaohao/valuation
  TAG: ${{ github.sha }}
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker stop valuation-web && docker rm valuation-web
            docker image prune -a
            docker pull ${{ env.IMAGE }}:${{ env.TAG }}
            docker run -itd --name valuation-web -p 4000:80 --restart=always ${{ env.IMAGE }}:${{ env.TAG }}
